version: "3.9"

services:
  app:
    build: .
    container_name: student-crud-app
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"

  postgres:
    image: postgres:15
    container_name: student-crud-db
    restart: always
    env_file:
      - .env
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
